// Automatically generated by via-profit/ability
// Do not edit manually
export type Resources = {
  ['always']: undefined;
  ['contains']: {
    readonly user: {
      readonly tags: readonly string[];
    };
  };
  ['document.create']: {
    readonly document: {
      readonly cteated: unknown;
      readonly ownerId: unknown;
      readonly status: string;
    };
    readonly user: {
      readonly id: unknown;
    };
  };
  ['document.read']: {
    readonly document: {
      readonly ownerId: unknown;
      readonly status: string;
    };
    readonly user: {
      readonly id: unknown;
    };
  };
  ['equals']: {
    readonly user: {
      readonly age: number;
      readonly name: string;
      readonly stateOn: boolean;
      readonly surname: string;
    };
  };
  ['greaterThanOrEqual']: {
    readonly user: {
      readonly age: number;
    };
  };
  ['gte']: {
    readonly user: {
      readonly age: number;
    };
  };
  ['in']: {
    readonly user: {
      readonly age: number;
      readonly role: string;
    };
  };
  ['isnotnull']: {
    readonly user: {
      readonly name: null | unknown;
      readonly surname: null | unknown;
    };
  };
  ['isnull']: {
    readonly user: {
      readonly middleName: null | unknown;
      readonly surname: null | unknown;
    };
  };
  ['istrue']: {
    readonly user: {
      readonly statusOn: boolean;
    };
  };
  ['length']: {
    readonly user: {
      readonly name: string | readonly unknown[];
    };
  };
  ['lengthGte']: {
    readonly user: {
      readonly name: string | readonly unknown[];
      readonly roles: string | readonly unknown[];
    };
  };
  ['lengthLessThan']: {
    readonly user: {
      readonly name: string | readonly unknown[];
      readonly roles: string | readonly unknown[];
    };
  };
  ['less']: {
    readonly user: {
      readonly age: number;
      readonly vol: number;
    };
  };
  ['lessThan']: {
    readonly user: {
      readonly name: number;
    };
  };
  ['mut.client.delete']: {
    readonly account: {
      readonly roles: readonly string[];
    };
    readonly client: {
      readonly name: string;
    };
  };
  ['mut.order.delete']: {
    readonly account: {
      readonly roles: readonly string[];
    };
    readonly order: {
      readonly createdHourLef: number;
    };
  };
  ['never']: undefined;
  ['notEquals']: {
    readonly user: {
      readonly age: number;
    };
  };
  ['notcontains']: {
    readonly user: {
      readonly tags: readonly string[];
    };
  };
  ['notin']: {
    readonly user: {
      readonly role: string;
    };
  };
}


export type PolicyTags = 'client' | 'mutation' | 'order';


export type Environment = {
  ['document.create']: {
    readonly createdAt: unknown;
  };
  ['mut.order.delete']: {
    readonly hour: number;
    readonly time: {
      readonly hour: number;
    };
  };
}
