// Automatically generated by via-profit/ability
// Do not edit manually
export type Resources = {

 /**
  * Permission: always
  * Effects: permit
  * Policies:
  *   - permit p_e293824600  "Unnamed policy"
  */
  ['always']: undefined;

 /**
  * Permission: contains
  * Effects: permit
  * Policies:
  *   - permit p_60e2e8e012  "Unnamed policy"
  */
  ['contains']: {
    readonly user: {
      readonly tags: readonly string[] | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: document.create
  * Effects: permit
  * Policies:
  *   - permit p_11b99ccedb  "Unnamed policy"
  */
  ['document.create']: {
    readonly document: {
      readonly cteated: unknown 
      readonly ownerId: unknown 
      readonly status: string | null | undefined 
    } | null | undefined;
    readonly user: {
      readonly id: unknown 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: document.read
  * Effects: permit
  * Policies:
  *   - permit p_01f9230098  "Unnamed policy"
  */
  ['document.read']: {
    readonly document: {
      readonly ownerId: unknown 
      readonly status: string | null | undefined 
    } | null | undefined;
    readonly user: {
      readonly id: unknown 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: equals
  * Effects: permit
  * Policies:
  *   - permit p_3f254d9281  "Unnamed policy"
  */
  ['equals']: {
    readonly user: {
      readonly age: number | null | undefined 
      readonly name: string | null | undefined 
      readonly stateOn: boolean | null | undefined 
      readonly surname: string | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: greaterThanOrEqual
  * Effects: permit
  * Policies:
  *   - permit p_d5236f6b14  "Unnamed policy"
  */
  ['greaterThanOrEqual']: {
    readonly user: {
      readonly age: number | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: gte
  * Effects: permit
  * Policies:
  *   - permit p_634804142f  "Unnamed policy"
  */
  ['gte']: {
    readonly user: {
      readonly age: number | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: in
  * Effects: permit
  * Policies:
  *   - permit p_8397f20457  "Unnamed policy"
  */
  ['in']: {
    readonly user: {
      readonly age: number | null | undefined 
      readonly role: string | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: isnotnull
  * Effects: permit
  * Policies:
  *   - permit p_00c58ad939  "Unnamed policy"
  */
  ['isnotnull']: {
    readonly user: {
      readonly name: null | unknown 
      readonly surname: null | unknown 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: isnull
  * Effects: permit
  * Policies:
  *   - permit p_0df64e439d  "Unnamed policy"
  */
  ['isnull']: {
    readonly user: {
      readonly middleName: null | unknown 
      readonly surname: null | unknown 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: istrue
  * Effects: permit
  * Policies:
  *   - permit p_7344f0557d  "Unnamed policy"
  */
  ['istrue']: {
    readonly user: {
      readonly statusOn: boolean | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: length
  * Effects: permit
  * Policies:
  *   - permit p_d98c6cc39d  "Unnamed policy"
  */
  ['length']: {
    readonly user: {
      readonly name: string | readonly unknown[] 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: lengthGte
  * Effects: permit
  * Policies:
  *   - permit p_c598ef5d1d  "Unnamed policy"
  */
  ['lengthGte']: {
    readonly user: {
      readonly name: string | readonly unknown[] 
      readonly roles: string | readonly unknown[] 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: lengthLessThan
  * Effects: permit
  * Policies:
  *   - permit p_83aa02ec60  "Unnamed policy"
  */
  ['lengthLessThan']: {
    readonly user: {
      readonly name: string | readonly unknown[] 
      readonly roles: string | readonly unknown[] 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: less
  * Effects: permit
  * Policies:
  *   - permit p_8d70b4a8c5  "Unnamed policy"
  */
  ['less']: {
    readonly user: {
      readonly age: number | null | undefined 
      readonly vol: number | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: lessThan
  * Effects: permit
  * Policies:
  *   - permit p_84bb29be1f  "Unnamed policy"
  */
  ['lessThan']: {
    readonly user: {
      readonly name: number | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: mut.client.delete
  * Effects: deny, permit
  * Policies:
  *   - deny   p_37b5eafb95  "Cant remove unnamed clients"
  *   - permit p_f87892c2e9  "ClientDeleteAccess"
  */
  ['mut.client.delete']: {
    readonly account: {
      readonly roles: readonly string[] | null | undefined 
    } | null | undefined;
    readonly client: {
      readonly name: string | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: mut.order.delete
  * Effects: deny, permit
  * Policies:
  *   - permit p_4784df1936  "OrderDeleteAccess"
  *   - deny   p_6c863096aa  "Unnamed policy"
  */
  ['mut.order.delete']: {
    readonly account: {
      readonly roles: readonly string[] | null | undefined 
    } | null | undefined;
    readonly order: {
      readonly createdHourLef: number | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: never
  * Effects: permit
  * Policies:
  *   - permit p_938130c7ae  "Unnamed policy"
  */
  ['never']: undefined;

 /**
  * Permission: notEquals
  * Effects: permit
  * Policies:
  *   - permit p_8c6aae29a4  "Unnamed policy"
  */
  ['notEquals']: {
    readonly user: {
      readonly age: number | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: notcontains
  * Effects: permit
  * Policies:
  *   - permit p_e14ba4479c  "Unnamed policy"
  */
  ['notcontains']: {
    readonly user: {
      readonly tags: readonly string[] | null | undefined 
    } | null | undefined;
  } | null | undefined;

 /**
  * Permission: notin
  * Effects: permit
  * Policies:
  *   - permit p_2474f6ceb9  "Unnamed policy"
  */
  ['notin']: {
    readonly user: {
      readonly role: string | null | undefined 
    } | null | undefined;
  } | null | undefined;
}


export type PolicyTags = 'client' | 'mutation' | 'order';


export type Environment = {

 /**
  * Permission: document.create
  * Effects: permit
  * Policies:
  *   - permit p_11b99ccedb  "Unnamed policy"
  */
  ['document.create']: {
    readonly createdAt: unknown 
  } | null | undefined;

 /**
  * Permission: mut.order.delete
  * Effects: deny, permit
  * Policies:
  *   - permit p_4784df1936  "OrderDeleteAccess"
  *   - deny   p_6c863096aa  "Unnamed policy"
  */
  ['mut.order.delete']: {
    readonly hour: number | null | undefined 
    readonly time: {
      readonly hour: number | null | undefined 
    } | null | undefined;
  } | null | undefined;
}
