import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const targetFile = path.join(__dirname, '..', '__test__', 'integration', 'types.gen.ts');
const fileContent = `
// Automatically generated by via-profit/ability
// Do not edit manually
export type Resources = {}
export type Environment = {}
export type PolicyTags = '';
`;


if (!fs.existsSync(targetFile)) {
  const dir = path.dirname(targetFile);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  

  fs.writeFileSync(targetFile, fileContent, 'utf8');
  console.log(`✅ Created ${targetFile}`);
} else {
  console.log(`ℹ️ ${targetFile} already exists, skipping...`);
}